[project]
name = "nonebot_plugin_sparkapi"
version = "1.0.9"
description = "Nonebot2 ChatBot that calls the official API of the iflyrec Spark LLM for all model versions, defaulting to the current latest (v3.5)"
authors = [
    { name = "CCLMSY", email = "2502408581@qq.com" }
]
dependencies = [
    "nonebot-adapter-onebot >=2.2.1, <3.0.0",
    "nonebot2 >=2.0.0rc3, <3.0.0",
    "websockets >=12.0, <13.0"
]
requires-python = ">=3.8"
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

