[project]
name = "nonebot_plugin_sparkapi"
version = "1.0.1"
description = "Nonebot2 ChatBot that calls the official API of the KDDI Spark LLM for all model versions, defaulting to the current latest (v3.5)"
authors = [
    { name = "CCLMSY", email = "2502408581@qq.com" }
]
dependencies = [
    "nonebot2 >=2.0.0rc3, <3.0.0",
    "nonebot-adapter-onebot >=2.2.1, <3.0.0",
    "websocket-client >=1.6.1, <2.0.0"
]
requires-python = ">=3.8"
license = { file = "LICENSE" }
readme = "README.md"
readme-content-type = "text/markdown"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
